apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  labels:
    app: sample-python-app
spec:
  replicas: 2                  #No of instances of pods for our application
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
      - name: python-app
        image: shubham315/simple-python-flask-app:latest
        volumeMounts:
          - name: db-connection
            mountPath: /opt
        ports:
        - containerPort: 80
      volumes:
        - name: db-connection
          configMap:
            name: test-cm
