kind: StatefulSet
apiVersion: apps/v1
  name: mysql-statefulset
  namespace: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  templates:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
      image: mysql:8.0
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_Password
        value: root

      - name: MYSQL_DATABASE
        value: devops

      volumeMounts:
      - name: mysql-data
        mountPath: /var/lib/mysql
    volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        
  
