apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-no-auth
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: http.svc
            port:
              number: 80
  
