kind: CronJob
apiVersion: batch/v1
metadata:
  name: minute-backup
  namespace: nginx

#spec of Cron Job starts here
spec:
  schedule: "* * * * *"     #take backup every 2nd min. run task every 2nd min
  jobTemplate:
    spec:                      #job template spec, template of single task (job)
      template:
        metadata:
          name: minute-backup
        labels:
          app: minute-backup

        spec:
          containers:
          - name: minute-backup-container
            image: busybox
            command: 
            - sh
            - -c
            - > 
              echo "Backup Started" ;
              mkdir -p /backups &&
              mkdir -p /data &&
              cp -r  /data /backup &&
              echo "Backup Completed";
            volumeMounts:
              - name: data-volume
                mountPath: /data
              - name: backup-volume
                mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: data-volume
              hostPath :
                path: /data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath :
                path: /backups
                type: DirectoryOrCreate
