
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loval-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 1Gi

  storageClassName: local-storage
  hostPath:  
    path: /mnt/data
