kind: PersistentVolume
apiVersion: v1
metadata:
  name: loval-pv
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostpath:  
    path: /mnt/data
